### ISSUE TITLE
How to specify NiftyNotificationView position?

### ISSUE THREAD

**Issue by yangjiheng** [sd6352051/NiftyNotification#10]
Hi,

First of all, thank you very much for the good work and sharing it to all of us. I tried the component, and it's working well. But according to the APIs available, I can only show the nitification on top of the layout, but cannot show it at any specific location that I want (for instance center of the screen, for some specific product requirements). 

So I'm wondering whether it's designed this way, or I haven't found how to do it yet.

Thanks again.

**Comment by sd6352051** [comment]
Notify view shown in the following layout,You can change this layout position,

https://github.com/sd6352051/NiftyNotification/blob/master/app/src/main/res/layout/activity_main.xml#L65-L71
