### ISSUE TITLE
NiftyNotification starts after 5-10 second delay.

### ISSUE THREAD

**Issue by ashokslsk** [sd6352051/NiftyNotification#14]
Hi @sd6352051 great library but the notification starts after 10 seconds of my successful API call is their anyway that i can show notification immediately.

My project is also taking time load the library i have no idea why this is happening please help.

Time to load native libraries: 3 ms (timestamps 6445-6448)
com.dunst.flutter I/cr.library_loader: Expected native library version number "46.0.2490.76", actual native library version number "46.0.2490.76"
 Background sticky concurrent mark sweep GC freed 18912(1711KB) AllocSpace objects, 0(0B) LOS objects, 4% free, 36MB/38MB, paused 18.953ms total 54.001ms

**Comment by litao0621** [comment]
Hi @ashokslsk Could you please paste your code snippet?
