### ISSUE TITLE
how to create animation before dismiss dialog

### ISSUE THREAD

**Issue by DoaiNguyen** [sd6352051/NiftyNotification#16]
This library is very useful and it helped to me very much. thank you very much.
Now, i want to create animation before dismiss dialog. I had try to override dismiss() and onDismissListener() method, but it's not work.
Help me! Thank you.

**Comment by litao0621** [comment]
Are you talking about [this ](https://github.com/sd6352051/NiftyDialogEffects) repository?  
NiftyDialogEffects is deprecated  you'd better use Android new API Dialog. 
Perhaps call this method `dialog.getWindow().setWindowAnimations(your animation style)` to add an animation effect is better
