### ISSUE TITLE
Add to Maven Central or jCenter

### ISSUE THREAD

**Issue by johnjohndoe** [sd6352051/NiftyNotification#5]
Please add your library to one of the common repositories such as *Maven Central* or *jCenter* to allow simplified usage via Gradle.

**Comment by dant3** [comment]
+1

**Comment by jitpack-io** [comment]
Btw, it's available right now on JitPack https://jitpack.io/#sd6352051/NiftyNotification/f50bcafe63

would be also great if there was a GitHub release @sd6352051

**Comment by sd6352051** [comment]
hi @jitpack-io 
I add you username to collaborators,thanks

**Comment by jitpack-io** [comment]
Hi @sd6352051! Awesome! Added new release and Maven/Gradle dependency info to readme. Happy to add this to other projects if you're interested.

**Comment by litao0621** [comment]
@jitpack-io 
sure,thank you for you help me to rebuld and maintain the project's,I don't have much time lately,collaborator on my all project now :smile: 

@johnjohndoe @dant3 support Gradle  now

**Comment by johnjohndoe** [comment]
:+1:

**Comment by litao0621** [comment]
hi @johnjohndoe  
Are you interested in continue this project.i can add your username to collaborator :D

**Comment by johnjohndoe** [comment]
@sd6352051 Thank you for the honour. But I know that it goes along with a lot of work. I won't have time to maintain the project since I have own stuff running.
