### ISSUE TITLE
Toast goes behind when Fragment changes 

### ISSUE THREAD

**Issue by Hesamedin** [sd6352051/NiftyNotification#6]
Hi Friend, me again ;)

I have an issue and hope you have an idea :)

I have an activity. This activity contains two fragments. When activity launches first fragment displays and I display a text message as NiftyToast on top of page. Everything is working fine here.

When user click on any item in menu then first fragment replaces by second fragment. Now the problem is since NiftyToast is not context aware it is not remove from the screen. However, the bigger problem is it goes behind second fragment. 

Is it possible that I always show NiftyTost on top of screen? This is an screenshot for your reference. Thanks.

![02](https://cloud.githubusercontent.com/assets/1493510/5224549/5880e5aa-7711-11e4-9ee4-b52140d0083a.png)

**Comment by MostafaAnter** [comment]
just  put your fragment id instead of layout id
